### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Core2002** [songangweb/durl#1]
2021/07/09 18:54:04.607 [E] [db.go:58]  Action xormDbStruct.GetQueueListById, err:  Error 1146: Table 'durl.durl_queue' doesn't exist

**Comment by songangweb** [comment]
表结构为:

CREATE TABLE `durl_queue` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `short_num` int(11) NOT NULL COMMENT '短链num',
  `is_del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0 正常 1 删除',
  `create_time` int(10) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(10) NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='处理列表';

CREATE TABLE `durl_short_num` (
  `id` tinyint(11) unsigned NOT NULL AUTO_INCREMENT,
  `max_num` int(11) NOT NULL DEFAULT '1' COMMENT '号码段开始值',
  `step` int(11) NOT NULL DEFAULT '1' COMMENT '步长',
  `version` int(11) NOT NULL DEFAULT '1' COMMENT '版本号',
  `update_time` int(11) NOT NULL DEFAULT '0' COMMENT '数据修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='短链号码段';


CREATE TABLE `durl_url` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `short_num` int(11) NOT NULL COMMENT '短链num',
  `full_url` varchar(255) NOT NULL DEFAULT '' COMMENT '完整链接',
  `expiration_time` int(11) NOT NULL DEFAULT '0' COMMENT '过期时间',
  `is_del` tinyint(1) NOT NULL DEFAULT '0' COMMENT '数据状态: 0 正常 1 删除',
  `is_frozen` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'url是否被冻结: 0 正常 1 被冻结',
  `create_time` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `update_time` int(11) NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='短链表';


**  durl_short_num 表需要插入一条数据
INSERT INTO durl_short_num  VALUES  (1, 1,100,1,1625831853);

**Comment by songangweb** [comment]
新版本已带自动同步表结构

**Comment by songangweb** [comment]
新版本已带自动同步表结构,可以提前创建,初次使用时也可以自动创建对应表
