### ISSUE TITLE
生成短链接后，跳转的地址为http://0.0.0.0:8082/f5v，怎么配置域名让外网可以正常跳转？

### ISSUE THREAD

**Issue by jacknotes** [songangweb/durl#14]
生成短链接后，跳转的地址为http://0.0.0.0:8082/f5v，怎么配置域名让外网可以正常跳转？

![image](https://user-images.githubusercontent.com/58760465/195299020-b7b400e2-861f-4199-b020-2c1a5d39c25b.png)

**Comment by songangweb** [comment]
protal项目  conf文件 jumpUrl  可以修改生成的跳转域名 现有默认的为 0.0.0.0:8082

**Comment by jacknotes** [comment]
好的。已经可以了。谢谢
